pbchallenge/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('testrunner.urls')),
]

# really rough implementation of the auth system using django admin
# TEMPLATES
urlpatterns += [
    url(r'^accounts/login/$', login, {'template_name': 'admin/login.html'}),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

# adds a login for the rest api pages
urlpatterns += [
    url(r'^api/auth/', include('rest_framework.urls',
        namespace='rest_framework')),
]

testrunner/urls.py
from django.conf.urls import url
from django.conf.urls import include
from rest_framework.urlpatterns import format_suffix_patterns

# app views
from testrunner import views

urlpatterns = [
    url(r'^$', views.create_instance),
    url(r'^create_testrun/', views.create_testrun, name="index"),
    url(r'^run/(?P<pk>[0-9]+)/$', views.display_testruni, name="display-instance"),
    url(r'^update_modules/', views.update_modules),
    url(r'^api/exec_test/', views.execute_test),
    url(r'^api/logs/', views.get_logs),
    url(r'^api/testruns/$', views.TestRunList.as_view(), name="api-testruns"),
    url(r'^api/testruns/(?P<pk>[0-9]+)/$', views.TestRunDetail.as_view()),
    url(r'^api/envs/$', views.TestEnvironmentList.as_view(), name='api-envs'),
    url(r'^api/envs/(?P<pk>[0-9]+)/$', views.TestEnvironmentDetail.as_view()),
    url(r'^api/runs/$', views.TestRunInstanceList.as_view(), name="api-instances"),
    url(r'^api/runs/(?P<pk>[0-9]+)/$', views.TestRunInstanceDetail.as_view()),
    url(r'^api/users/$', views.UserList.as_view(), name="api-users"),
    url(r'^api/users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

testrunner/models.py
from datetime import datetime

from django.db import models

INTERFACE_CHOICES = (
    ('ssh', 'ssh'),
    ('lfs', 'local'),
)

RESULT_CHOICES = (
    ('PASSED', 'PASSED'),
    ('FAILED', 'FAILED'),
    ('ERROR', 'ERROR'),
)

STATUS_CHOICES = (
    ('stopped', 'stopped'),
    ('running', 'running'),
)

STATE_CHOICES = (
    ('idle', 'idle'),
    ('inuse', 'inuse'),
)

# Create your models here.
class TestEnvironment(models.Model):
    host = models.CharField(max_length=100, default='localhost')
    state = models.CharField(   choices=STATE_CHOICES,
                                max_length=20,
                                default='idle')

    class Meta:
        app_label = "testrunner"

    def __str__(self):
        return "id: {}, host: {}".format(self.id, self.host)


class TestModule(models.Model):
    """ A reference to a file that contains one or more tests and exists
    the specified testing directory. """

    class Meta:
        app_label = "testrunner"

    path = models.CharField(max_length=100, unique=True)

    last_result = models.CharField(  choices=RESULT_CHOICES,
                                     max_length=20,
                                     null=True )


class TestRun(models.Model):
    """
    A model to be used as a launch point to create a testrun instance.
    """

    class Meta:
        app_label = "testrunner"

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200, null=True)
    modules = models.ManyToManyField(TestModule, blank=False)

    """
    The below attributes should only be set by the system after a child
    TestRunInstance completes
    """

    last_run = models.DateTimeField(null=True)

    last_result = models.CharField( choices=RESULT_CHOICES,
                                    max_length=20,
                                    null=True )

    created_by = models.ForeignKey( 'auth.User',
                                    related_name='testruns',
                                    on_delete=models.CASCADE,
                                    null=False )
    created_on = models.DateTimeField(default=datetime.now)


    def save(self, *args, **kwargs):
        """
        Extra steps to perform before the object is saved to the DB
        """
        super(TestRun, self).save(*args, **kwargs)


    def __str__(self):
        return self.name


class TestRunInstance(models.Model):
    """
    Instance of a TestRun that has or will be executed
    """

    requested_by = models.ForeignKey('auth.User', blank=True, null=True)

    testrun = models.ForeignKey(TestRun)

    status = models.CharField(  choices=STATUS_CHOICES,
                                default="stopped",
                                max_length=20 )

    interface = models.CharField( choices=INTERFACE_CHOICES,
                                  default='ssh',
                                  max_length=20 )

    environment = models.ForeignKey(TestEnvironment)

    result = models.CharField(  choices=RESULT_CHOICES,
                                max_length=20,
                                null=True )

    output = models.CharField(max_length=65000, null=True)

    executed_on = models.DateTimeField(null=True)

    created_on = models.DateTimeField(default=datetime.now)

    class Meta:
        app_label = "testrunner"
        ordering = ('-created_on', 'executed_on')


class Template(models.Model):
    """ A collection of tests. When attached to a TestRun, adds each Test
    individually."""

    class Meta:
        app_label = "testrunner"

    label = models.CharField(max_length=40, unique=True, null=False)
    modules = models.ManyToManyField(TestModule)

testrunner/forms.py
from django import forms
from django.forms import ModelForm
from testrunner.models import TestRunInstance, TestRun, TestModule, TestEnvironment


class TestRunInstanceForm(ModelForm):
    class Meta:
        model = TestRunInstance
        fields = ['testrun', 'interface', 'environment']


class TestEnvironmentForm(ModelForm):
    class Meta:
        model = TestEnvironment
        fields = ['host']


class TestRunForm(ModelForm):
    # Representing the many to many related field in TestRun
    modules = forms.ModelMultipleChoiceField(queryset=TestModule.objects.all())

    class Meta:
        model = TestRun
        fields = ['name', 'description', 'modules']

testrunner/views.py
import json, os, re
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

# REST API imports
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics
from rest_framework import permissions

# app models
from testrunner.models import TestRun
from testrunner.models import TestRunInstance
from testrunner.models import TestEnvironment
from testrunner.models import TestModule
from django.contrib.auth.models import User

# serializers
from testrunner.serializers import TestRunSerializer
from testrunner.serializers import TestRunInstanceSerializer
from testrunner.serializers import TestEnvironmentSerializer
from testrunner.serializers import UserSerializer

# forms
from testrunner.forms import TestRunInstanceForm, TestRunForm, TestEnvironmentForm

# utlities
from testrunner.helpers import create_hierarchy, get_test_modules, execute_test_django
from testrunner.helpers import TESTS_DIR

@login_required
def get_logs(request):

    if request.method == 'GET':
        iid = request.GET.get('instance_id')

        instance = TestRunInstance.objects.filter(id=iid)[0]
        response_data = {}
        response_data['logs_content'] = ""
        for m in instance.testrun.modules.all():
            # HACK fix module path at POST
            m.path = m.path.replace('./', '')
            dir = "{}logs/{}/".format(TESTS_DIR, iid)
            filename = "{}{}".format(TESTS_DIR, m.path)
            # make replacements to match logfile name on disk
            filename = filename.replace('/', '.')
            filename = filename.replace('.py', '.log')
            filename = dir + filename
            # open log file and return contents
            with open(filename, 'r') as log_file:
                response_data['logs_content'] += log_file.read()

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"error": "error"}),
            content_type="application/json"
        )

# views
@login_required
def execute_test(request):
    """
    This view is designed to take a POST request and return a
    JSON response after executing the posted test module.

    Time allowing, we would put this into an APIView class so the testrunner
    code doesn't live in helpers.py
    """
    if request.method == 'POST':

        module_id = request.POST.get('m_id')
        instance_id = request.POST.get('run_id')

        # the dictionary to be JSON encoded
        response_data = {}

        # use the posted ID to pull the test module
        module = TestModule.objects.filter(id=module_id)[0]

        # send the path to the helper that actually runs the test
        response_data['output'] = execute_test_django(module.path, instance_id)
        response_data['pk'] = module.id
        response_data['path'] = module.path

        # find the result. a single fail means the run fails
        output = response_data['output']

        # find all before the first newline
        m = re.search(r"(.*)\n", output, re.M)
        if m and ('F' in m.group(1) or 'E' in m.group(1)):
            response_data['result'] = 'FAILED'
        else:
            response_data['result'] = 'PASSED'

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"error": "error"}),
            content_type="application/json"
        )


@login_required
def update_modules(request):
    """
    This is a temporary method while developing to help
    populate the TestModule DB from a filesystem. It would be
    protected and added to a control panel in prod. This code
    would move to a utlities module.
    """
    #TestModule.objects.all().delete()
    # create the list to hold the TestModule list
    module_l = list()
    # get a list of test modules
    _tmodules = get_test_modules('testrunner/tests/')
    for m in _tmodules:
        module_l.append(TestModule(path=m))

    # create all modules in bulk, should purge first TODO
    TestModule.objects.bulk_create(module_l)

    tmodules = TestModule.objects.all()

    template = "testrunner/update_modules.html"
    context = {
        'modules':tmodules,
    }

    return render(request, template, context)

@login_required
def display_testruni(request, pk):
    """
    Display and run a single testrun instance.
    """
    context = {}
    template = 'testrunner/display_testruni.html'

    # create queryset to hold all current testrun instances
    testrun_instance = TestRunInstance.objects.filter(id=pk)[0]
    modules = testrun_instance.testrun.modules.all()

    if request.method == 'POST':
        # updated the model with the test run result
        testrun_instance.output = request.POST.get('instance_output')
        testrun_instance.executed_on = datetime.now()

        # iterate through the attached modules and check their
        # result. If one fails, the run fails
        mids = list()
        for m in modules:
            field_id = "test-module--{}".format(m.id)
            mids.append(m.id)
            if request.POST.get(field_id) == 'FAILED':
                # break out, as a single failure means the run fails
                testrun_instance.result = 'FAILED'
                break
            else:
                testrun_instance.result = 'PASSED'
        context.update({'mids':mids})
        testrun_instance.save()

    # create queryset to hold all current testrun instances
    testruns = TestRunInstance.objects.all()

    context.update({
        'testrun_current': testrun_instance,
        'modules': modules,
        'testruns': testruns,
    })

    return render(request, template, context)

@login_required
def create_testrun(request):
    """
    Parse the create_testrun form and save, then re-direct to the
    index screen.
    """
    if request.method == 'POST':
        testrun_form = TestRunForm(request.POST)

        # replace file name with pk of module
        if testrun_form.is_valid():
            form = testrun_form.save(commit=False)
            form.created_by = request.user
            form.save()
            testrun_form.save_m2m()

            # get the last entered TestRun
            added = TestRun.objects.latest('id')

            # go to index
            return HttpResponseRedirect('/?tr={}'.format(added.id))
        else:
            # we should redirect to the index and pass a GET
            # variable to tell the user there was an error.
            # preferably open the form modal first and display.
            # return HttpResponseRedirect('/?errcode=1')
            template = "testrunner/form_errors.html"
            context = { 'form': testrun_form }
            return render(request, template, context)

    else:
        # immediately redirect the user, this page is only for
        # processing (with the goal of AJAXing the entire process.)
        return HttpResponseRedirect('/')


@login_required
def create_instance(request):
    """
    Create and run an instance of a TestRun, or create a new TestRun
    first and then run an instance.

    Also, display previous test run results.
    """
    context = {}
    template = 'testrunner/create_instance.html'

    # create queryset to hold all current testrun instances
    testruns = TestRunInstance.objects.all()

    # instance of the TestEnvironmentForm for our modal
    testenv_form = TestEnvironmentForm(request.POST)

    # generate the test modules hierarchy
    tmodules = get_test_modules('testrunner/tests')

    # build a nested dictionary hierarchy of the filesystem
    fs_hierarchy = create_hierarchy(tmodules)

    if request.method == 'POST':
        instance_form = TestRunInstanceForm(request.POST)
        testrun_form = TestRunForm(request.POST)

        if instance_form.is_valid():
            form = instance_form.save(commit=False)
            form.requested_by = request.user
            form.save()

            # assume save was successful...
            # TODO more defensive coding
            # pull the last entered instance
            testrun_instance = TestRunInstance.objects.latest('id')
            modules = testrun_instance.testrun.modules.all()
            context.update({
                'testrun_current':testrun_instance,
                'modules':modules,
            })
    else:
        # set the initial to the passed in GET var, or just 0
        instance_form = TestRunInstanceForm(
            initial={'testrun': request.GET.get('tr', 0)},
            label_suffix=':')

        # create a testrun_form for the 'add new' modal
        testrun_form = TestRunForm()

        # add the forms to page context
        context.update({
            'form': instance_form,
            'trform': testrun_form,
            'teform': testenv_form,
        })

    context.update({
        'testruns': testruns,
        'files': fs_hierarchy,
    })

    return render(request, template, context)


class TestRunList(APIView):
    """
    List all available test runs, or create a new test run.
    """

    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = TestRunSerializer

    def get(self, request, format=None):
        testruns = TestRun.objects.all()
        serializer = TestRunSerializer(testruns, many=True)

        return Response(serializer.data)


    def post(self, request, format=None):
        serializer = TestRunSerializer(data=request.data)

        if serializer.is_valid():
            serializer.save(created_by=self.request.user)

            return Response(serializer.data, \
                status=status.HTTP_201_CREATED)

        return Response(serializer.errors, \

testrunner/templates/testrunner/modals/testenvironment.html
{% if teform %}
{% load widget_tweaks %}
<!-- Dialog window for adding a new TestEnvironment -->
<aside id="mdc-dialog-for-tenvf"
  class="mdc-dialog"
  role="alertdialog"
  aria-labelledby="mdc-dialog-with-list-label"
  aria-describedby="mdc-dialog-with-list-description">
  <div class="mdc-dialog__surface">
    <header class="mdc-dialog__header">
      <h2 id="mdc-dialog-with-list-label" class="mdc-dialog__header__title">
        Create an Environment
      </h2>
    </header>
    <form action="#" method="POST" name="create-testenv-form" id="create-testenv-form">
      {% csrf_token %}
      <section id="mdc-dialog-with-list-description" class="mdc-dialog__body mdc-dialog__body--scrollable">
       	<ul class="mdc-list">
          <li class='mdc-list-item'>
            <div class="mdc-textfield mdc-textfield--fullwidth mdc-textfield--upgraded" data-demo-no-auto-js="">
              {{ teform.host|attr:"class:mdc-textfield__input"|attr:"placeholder:Host"|attr:"aria-label:Host" }}
            </div>
          </li>
        </ul>

      <footer class="mdc-dialog__footer">
        <button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--cancel">Cancel</button>
        <button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--accept">Submit</button>
      </footer>
    </form>
  </div>
  <div class="mdc-dialog__backdrop"></div>
</aside>

<script>
  // the create test run dialog window
  let dialog_te = new mdc.dialog.MDCDialog(document.querySelector('#mdc-dialog-for-tenvf'));

  dialog_te.listen('MDCDialog:accept', function() {
    console.log('accepted');

    // collect toSend data
    var host = $("#id_host").val();

    // submit the form
    $.ajax({
      // endpoint
      url : "/api/envs/",
      type : "POST",
      // data sent with the post request
      data : { "host" : host },

      // handle a successful response
      success : function(json) {
        console.log(json);

        // update the select
        // create the option target
        option_tag = $('<option></option>').val(json['id']);
        text = "id: " + json['id'] + ", host: " + json['host'];
        option_tag.html(text);

        // append to select
        $('#id_environment').append(option_tag);

        // set as selected
        $('#id_environment').val(json['id']);
      },
    });
  });

  dialog_te.listen('MDCDialog:cancel', function() {
    console.log('canceled');
  });

  // Show the modal with the TestEnvironment form
  document.querySelector('#te-form-show').addEventListener('click', function (evt) {
    dialog_te.lastFocusedTarget = evt.target;
    dialog_te.show();
  });
</script>
{% endif %}

testrunner/templates/testrunner/modals/testlogs.html
<!-- Dialog window for displaying testlogs -->
<aside id="mdc-dialog-for-logs"
  class="mdc-dialog"
  role="alertdialog"
  aria-labelledby="mdc-dialog-with-list-label"
  aria-describedby="mdc-dialog-with-list-description">
  <div class="mdc-dialog__surface">
    <header class="mdc-dialog__header">
      <h2 id="mdc-dialog-with-list-label" class="mdc-dialog__header__title">
        Log Output
      </h2>
    </header>
    <section id="mdc-dialog-for-output-body" class="mdc-dialog__body mdc-dialog__body-scrollable" style="overflow:scroll;">
      <pre id="test-logs-display"></pre>
    </section>
    <footer class="mdc-dialog__footer">
      <button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--cancel">Cancel</button>
      <button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--accept">Submit</button>
    </footer>
    </form>
  </div>
  <div class="mdc-dialog__backdrop"></div>
</aside>

<script>
  // the create test run dialog window
  let dialog_logs = new mdc.dialog.MDCDialog(document.querySelector('#mdc-dialog-for-logs'));
</script>

testrunner/templates/testrunner/modals/testoutput.html
<!-- Dialog window for showing test output -->
<aside id="mdc-dialog-for-output"
  class="mdc-dialog"
  role="alertdialog"
  aria-labelledby="mdc-dialog-for-output-header"
  aria-describedby="mdc-dialog-for-output-body">
  <div class="mdc-dialog__surface">
    <header class="mdc-dialog__header">
      <h2 id="mdc-dialog-for-output-header" class="mdc-dialog__header__title">
        Most Recent Output
      </h2>
    </header>
    <section id="mdc-dialog-for-output-body" class="mdc-dialog__body mdc-dialog__body-scrollable" style="overflow:scroll;">
      <pre id="test-output-display" style="padding:20px;"></pre>
    <section>
    <footer class="mdc-dialog__footer">
      <button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--cancel">Cancel</button>
      <button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--accept">Submit</button>
    </footer>
    </form>
  </div>
  <div class="mdc-dialog__backdrop"></div>
</aside>

<script>
  // the create test run dialog window
  let dialog_ouput = new mdc.dialog.MDCDialog(document.querySelector('#mdc-dialog-for-output'));

</script>

testrunner/templates/testrunner/modals/testrun.html
{% if trform %}
{% load widget_tweaks %}
<!-- Dialog window for adding a new TestRun -->
<aside id="mdc-dialog-for-testrunf"
  class="mdc-dialog"
  role="alertdialog"
  aria-labelledby="mdc-dialog-with-list-label"
  aria-describedby="mdc-dialog-with-list-description">
  <div class="mdc-dialog__surface">
    <header class="mdc-dialog__header">
      <h2 id="mdc-dialog-with-list-label" class="mdc-dialog__header__title">
        Create a Test Run
      </h2>
    </header>
    <form action="/create_testrun/" method="POST" name="create-testrun-form" id="create-testrun-form">
      {% csrf_token %}
      <section id="mdc-dialog-with-list-description" class="mdc-dialog__body mdc-dialog__body--scrollable">
       	<ul class="mdc-list">
          <li class='mdc-list-item'>
            <div class="mdc-textfield mdc-textfield--fullwidth mdc-textfield--upgraded" data-demo-no-auto-js="">
              {{ trform.name|attr:"class:mdc-textfield__input"|attr:"placeholder:Name"|attr:"aria-label:Name" }}
            </div>
          </li>
          <li class='mdc-list-item'>
            <div class="mdc-textfield mdc-textfield--fullwidth mdc-textfield--upgraded" data-demo-no-auto-js="">
              {{ trform.description|attr:"class:mdc-textfield__input"|attr:"placeholder:Description"|attr:"aria-label:Description" }}
            </div>
          </li>
        </ul>

        <!-- Multi-select for selecting tests to be executed -->
        <section class="tr-multi-select__section">
          <h3 class="mdc-typography--subheading2">
            Select test modules for execution:
          </h3>
          <div class="mdc-form-field mdc-form-field--align-end">
            <select multiple size="10" class="mdc-multi-select mdc-list" id="id__modules" name="_modules">
              {% with files=files template="testrunner/module_mselect.html" %}
                {% include template %}
              {% endwith %}
            </select>
            <div style="display:none">{{ trform.modules }}</div>
          </div>
        </section>

      <footer class="mdc-dialog__footer">
        <button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--cancel">Cancel</button>
        <button type="button" class="mdc-button mdc-dialog__footer__button mdc-dialog__footer__button--accept">Submit</button>
      </footer>
    </form>
  </div>
  <div class="mdc-dialog__backdrop"></div>
</aside>
<script>
// the create test run dialog window
let dialog_tr = new mdc.dialog.MDCDialog(document.querySelector('#mdc-dialog-for-testrunf'));

dialog_tr.listen('MDCDialog:accept', function() {
  console.log('accepted');

  // submit the form
  var the_form = document.querySelector('#create-testrun-form');
  the_form.submit();

});

dialog_tr.listen('MDCDialog:cancel', function() {
  console.log('canceled');
});

// Show the modal with the TestRun form
document.querySelector('#tr-form-show').addEventListener('click', function (evt) {
  dialog_tr.lastFocusedTarget = evt.target;
  dialog_tr.show();
});

var file_selector = document.querySelector('#id__modules').addEventListener('change', function(evt) {
  var sel = document.querySelector('#id_modules');
  var el = evt.currentTarget;

  for (var i = 0; i < el.options.length; i++) {
    // get the corresponding element form the real
    // modules element
    opt_a = sel.options[i];
    opt_b = el.options[i];

    // every element in the first select triggers the second\
    // to be selected
    if (opt_b.selected) {
      opt_a.selected = true;
    } else {
      opt_a.selected = false;
    }
  }
});
</script>
{% endif %}